In [1]:
import numpy as np

# Banking dataset (10 × 5)
customer_data = np.array([
    [1001, 15420, 720, 25, 8],
    [1002, 8430, 655, 12, 5],
    [1003, 19350, 810, 40, 15],
    [1004, 5620, 540, 7, 3],
    [1005, 12800, 690, 20, 6],
    [1006, 9750, 450, 15, 4],
    [1007, 17500, 780, 35, 12],
    [1008, 4200, 610, 9, 2],
    [1009, 16000, 730, 28, 9],
    [1010, 11000, 500, 18, 7]
])

print(customer_data)

type(customer_data)

[[ 1001 15420   720    25     8]
 [ 1002  8430   655    12     5]
 [ 1003 19350   810    40    15]
 [ 1004  5620   540     7     3]
 [ 1005 12800   690    20     6]
 [ 1006  9750   450    15     4]
 [ 1007 17500   780    35    12]
 [ 1008  4200   610     9     2]
 [ 1009 16000   730    28     9]
 [ 1010 11000   500    18     7]]


numpy.ndarray

In [ ]:

# | Customer\_ID | Account\_Balance | Credit\_Score | Transaction\_Count | Years\_Active |


Question 1: Array Creation and Manipulation


In [ ]:
# Q1.1: Create a 4x4 identity matrix using np.eye()

identity_matrix=np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Q1.2: Create an array of 8 zeros using np.zeros()

np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Q1.3: Create an array of 6 ones using np.ones()

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()

np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

np.linspace(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

Question 2: Array Attributes and Information


In [ ]:
# Q2.1: What is the shape of the banking_data array?

customer_data.shape

(10, 5)

In [ ]:
# Q2.2: What is the data type of the banking_data array?

customer_data.dtype

dtype('int64')

In [ ]:
# Q2.3: What is the size (total number of elements) of the banking_data array?

customer_data.size

50

In [ ]:
# Q2.4: What is the number of dimensions of the banking_data array?
customer_data.ndim


2

In [ ]:
# Q2.5: What is the memory size of the banking_data array in bytes?

customer_data.nbytes

400

Question 3: Indexing and Slicing


In [ ]:
# Q3.1: Extract the first row of banking_data

customer_data[0]

array([ 1001, 15420,   720,    25,     8])

In [ ]:
# Q3.2: Extract the last row of banking_data

customer_data[-1]

array([ 1010, 11000,   500,    18,     7])

In [ ]:
#Q3.3: Extract the Account_Balance column (column index 1)
frist_row=customer_data[:,1]
print(frist_row)

[15420  8430 19350  5620 12800  9750 17500  4200 16000 11000]


In [ ]:
#Q3.4: Extract the first 4 rows and first 3 columns

customer_data[:4,:3]

array([[ 1001, 15420,   720],
       [ 1002,  8430,   655],
       [ 1003, 19350,   810],
       [ 1004,  5620,   540]])

In [ ]:
# Q3.5: Extract rows 3 to 7 (inclusive)

customer_data[3:7]

array([[ 1004,  5620,   540,     7,     3],
       [ 1005, 12800,   690,    20,     6],
       [ 1006,  9750,   450,    15,     4],
       [ 1007, 17500,   780,    35,    12]])

Question 4: Mathematical Operations

In [ ]:
# Q4.1: Calculate the sum of all account balances
total_balances=customer_data[:,1]
print(total_balances)

[15420  8430 19350  5620 12800  9750 17500  4200 16000 11000]


In [ ]:
# Q4.2: Calculate the mean account balance
np.mean(customer_data[:,1])

np.float64(12007.0)

In [ ]:
# Q4.3: Calculate the standard deviation of account balances
np.std(customer_data[:,1])

np.float64(4826.595176726551)

In [ ]:
# Q4.4: Calculate the variance of account balances
np.var(customer_data[:,1])

np.float64(23296021.0)

In [ ]:
# Q4.5: Calculate the median account balance
np.median(customer_data[:,1])

np.float64(11900.0)

Question 5: Statistical Functions







In [ ]:
#  Q5.1: Find the minimum and maximum account balances -->
min_balance=np.min(customer_data[:,1])
max_balance=np.max(customer_data[:,1])
print(min_balance)
print(max_balance)

4200
19350


In [ ]:
# Q5.2: Find the minimum and maximum credit scores
min_scores=np.min(customer_data[:,2])
max_scores=np.max(customer_data[:,2])
print(min_scores)
print(max_scores)

450
810


In [ ]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
percentiles_balance=np.percentile(customer_data[:,1],[25,50,75])
print(f"25th percentile: ${percentiles_balance[0]}")
print(f"50th percentile: ${percentiles_balance[1]}")
print(f"75th percentile: ${percentiles_balance[2]}")

25th percentile: $8760.0
50th percentile: $11900.0
75th percentile: $15855.0


In [ ]:
# Q5.4: Calculate the correlation between account balance and credit score
correlation_value=np.corrcoef(customer_data[:,1],customer_data[:,2])[0,1]
print(correlation_value)

0.7365847625781543


In [ ]:
# Q5.5: Calculate the covariance between account balance and credit score
covariance_value=np.cov(customer_data[:,1],customer_data[:,2])[0,1]
print(covariance_value)

453161.6666666666


Question 6: Array Reshaping and Manipulation


In [ ]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshaped=customer_data.reshape((5,10))
print(reshaped)

[[ 1001 15420   720    25     8  1002  8430   655    12     5]
 [ 1003 19350   810    40    15  1004  5620   540     7     3]
 [ 1005 12800   690    20     6  1006  9750   450    15     4]
 [ 1007 17500   780    35    12  1008  4200   610     9     2]
 [ 1009 16000   730    28     9  1010 11000   500    18     7]]


In [ ]:
# Q6.2: Flatten the banking_data to a 1D array
customer_data.flatten()

array([ 1001, 15420,   720,    25,     8,  1002,  8430,   655,    12,
           5,  1003, 19350,   810,    40,    15,  1004,  5620,   540,
           7,     3,  1005, 12800,   690,    20,     6,  1006,  9750,
         450,    15,     4,  1007, 17500,   780,    35,    12,  1008,
        4200,   610,     9,     2,  1009, 16000,   730,    28,     9,
        1010, 11000,   500,    18,     7])

In [ ]:
# Q6.3: Transpose the banking_data
transpose_matrix=customer_data.T
print(transpose_matrix)

[[ 1001  1002  1003  1004  1005  1006  1007  1008  1009  1010]
 [15420  8430 19350  5620 12800  9750 17500  4200 16000 11000]
 [  720   655   810   540   690   450   780   610   730   500]
 [   25    12    40     7    20    15    35     9    28    18]
 [    8     5    15     3     6     4    12     2     9     7]]


In [ ]:
# Q6.4: Split the banking_data into 2 equal parts vertically
split_vertically=np.vsplit(customer_data,2)
print(split_vertically[0])
print( )
print(split_vertically[1])

[[ 1001 15420   720    25     8]
 [ 1002  8430   655    12     5]
 [ 1003 19350   810    40    15]
 [ 1004  5620   540     7     3]
 [ 1005 12800   690    20     6]]

[[ 1006  9750   450    15     4]
 [ 1007 17500   780    35    12]
 [ 1008  4200   610     9     2]
 [ 1009 16000   730    28     9]
 [ 1010 11000   500    18     7]]


In [ ]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
split_horizontally=np.hsplit(customer_data,2)
print(split_horizontally[0])
print( )
print(split_horizontally[1])

ValueError: array split does not result in an equal division

Question 7: Logical Operations and Filtering


In [ ]:
# Q7.1: Find customers with account balance greater than $100,000

balance_greater_100000=customer_data[customer_data[:,1]>100000]
print(balance_greater_100000)

[]


In [ ]:
# Q7.2: Find customers with credit score greater than 800

high_credit_customers=customer_data[customer_data[:,2]>800]
print(high_credit_customers )

[[ 1003 19350   810    40    15]]


In [ ]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750

h=customer_data[(customer_data[:,3]>50) & (customer_data[:,2]<750)]
print(h)

[]


In [ ]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
d=customer_data[(customer_data[:,1]>10000) & (customer_data[:,1]<100000)]

print(d)

[[ 1001 15420   720    25     8]
 [ 1003 19350   810    40    15]
 [ 1005 12800   690    20     6]
 [ 1007 17500   780    35    12]
 [ 1009 16000   730    28     9]
 [ 1010 11000   500    18     7]]


In [ ]:
# Q7.5: Find the index of the customer with the highest credit score
print(customer_data[:,2].argsort()[-1])


2


Question 8: Sorting and Searching


In [ ]:
# Q8.1: Sort the banking_data by account balance (ascending)

acending_order_balance=customer_data[customer_data[:,1].argsort()]
print(acending_order_balance)


[[ 1008  4200   610     9     2]
 [ 1004  5620   540     7     3]
 [ 1002  8430   655    12     5]
 [ 1006  9750   450    15     4]
 [ 1010 11000   500    18     7]
 [ 1005 12800   690    20     6]
 [ 1001 15420   720    25     8]
 [ 1009 16000   730    28     9]
 [ 1007 17500   780    35    12]
 [ 1003 19350   810    40    15]]


In [ ]:
# Q8.2: Sort the banking_data by credit score (descending)
descending_order_score=customer_data[customer_data[:,2].argsort()]
print(descending_order_score)

[[ 1006  9750   450    15     4]
 [ 1010 11000   500    18     7]
 [ 1004  5620   540     7     3]
 [ 1008  4200   610     9     2]
 [ 1002  8430   655    12     5]
 [ 1005 12800   690    20     6]
 [ 1001 15420   720    25     8]
 [ 1009 16000   730    28     9]
 [ 1007 17500   780    35    12]
 [ 1003 19350   810    40    15]]


In [ ]:
# Q8.3: Find the indices that would sort the array by years active
customer_data[:,4].argsort()

array([7, 3, 5, 1, 4, 9, 0, 8, 6, 2])

In [ ]:
# Q8.4: Find the customer with the second highest account balance
customer_data[customer_data[:,1].argsort()[-2]]

array([ 1007, 17500,   780,    35,    12])

In [ ]:
# Q8.5: Find the customer with the lowest transaction count
lowest=customer_data[customer_data[:,3].argsort()[0]]
print(lowest)

[1004 5620  540    7    3]


Question 9: Mathematical Functions


In [ ]:
# Q9.1: Calculate the absolute values of all elements
abs_values = np.abs(customer_data)
print("Q9.1 Absolute values:\n", abs_values)

Q9.1 Absolute values:
 [[ 1001 15420   720    25     8]
 [ 1002  8430   655    12     5]
 [ 1003 19350   810    40    15]
 [ 1004  5620   540     7     3]
 [ 1005 12800   690    20     6]
 [ 1006  9750   450    15     4]
 [ 1007 17500   780    35    12]
 [ 1008  4200   610     9     2]
 [ 1009 16000   730    28     9]
 [ 1010 11000   500    18     7]]


In [ ]:
# Q9.2: Calculate the square root of all account balances
sqrt_balance = np.sqrt(customer_data[:, 1])
print("\nQ9.2 Square root of Account Balances:\n", sqrt_balance)



Q9.2 Square root of Account Balances:
 [124.17729261  91.81503145 139.10427743  74.96665926 113.13708499
  98.74208829 132.28756555  64.80740698 126.49110641 104.88088482]


In [ ]:
# Q9.3: Calculate the square of all credit scores
square_credit = np.square(customer_data[:, 2])
print(square_credit)

[518400 429025 656100 291600 476100 202500 608400 372100 532900 250000]


In [ ]:
# Q9.4: Calculate the exponential of all transaction counts
exp_transactions = np.exp(customer_data[:, 3])
print(exp_transactions)

[7.20048993e+10 1.62754791e+05 2.35385267e+17 1.09663316e+03
 4.85165195e+08 3.26901737e+06 1.58601345e+15 8.10308393e+03
 1.44625706e+12 6.56599691e+07]


In [ ]:
# Q9.5: Calculate the natural logarithm of all account balances
log_balance = np.log(customer_data[:, 1])
print(log_balance)

[9.64342065 9.03955205 9.8704477  8.63408694 9.45720045 9.18502256
 9.76995616 8.3428398  9.680344   9.30565055]


Question 10: Advanced Operations


In [ ]:
# Q10.1: Calculate the cumulative sum of account balances
account_balances = customer_data[:, 1]
transaction_counts = customer_data[:, 3]

cumsum_balances = np.cumsum(account_balances)
print(cumsum_balances)

[ 15420  23850  43200  48820  61620  71370  88870  93070 109070 120070]


In [ ]:
# Q10.2: Calculate the cumulative product of transaction counts
cumprod_transactions = np.cumprod(transaction_counts)
print(cumprod_transactions)


[           25           300         12000         84000       1680000
      25200000     882000000    7938000000  222264000000 4000752000000]


In [ ]:
# Q10.3: Calculate the difference between consecutive account balances
diff_balances = np.diff(account_balances)
print(diff_balances)

[ -6990  10920 -13730   7180  -3050   7750 -13300  11800  -5000]


In [ ]:
# Q10.4: Calculate the gradient of account balances
gradient_balances = np.gradient(account_balances)
print(gradient_balances)

[-6990.  1965. -1405. -3275.  2065.  2350. -2775.  -750.  3400. -5000.]


In [ ]:
# Q10.5: Calculate the histogram of account balances with 5 bins

hist_counts, bin_edges = np.histogram(account_balances, bins=5)
print(hist_counts,bin_edges)

[2 2 2 2 2] [ 4200.  7230. 10260. 13290. 16320. 19350.]


Question 11: Random Numbers and Simulation


In [ ]:
# Q11.1: Generate 6 random integers between 1 and 1000
x=np.random.randint(1,1000,6)
print(x)






[ 23 306 685 896  76 162]


In [ ]:
# Q11.2: Generate 6 random floats between 0 and 1
random_floats = np.random.rand(6)
print( random_floats)


[0.72189693 0.74399486 0.02033234 0.21781426 0.69702324 0.2347192 ]


In [ ]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
random_normals = np.random.normal(loc=700, scale=100, size=6)
print(random_normals)


[812.59146085 786.83254304 662.1673312  648.3299112  594.90501044
 585.58817365]


In [ ]:
# Q11.4: Shuffle the banking_data rows randomly
np.random.seed(123)  # Fix seed
np.random.shuffle(customer_data)
print(customer_data)

[[ 1005 12800   690    20     6]
 [ 1001 15420   720    25     8]
 [ 1008  4200   610     9     2]
 [ 1006  9750   450    15     4]
 [ 1009 16000   730    28     9]
 [ 1004  5620   540     7     3]
 [ 1002  8430   655    12     5]
 [ 1007 17500   780    35    12]
 [ 1010 11000   500    18     7]
 [ 1003 19350   810    40    15]]


In [ ]:
# Q11.5: Set random seed to 123 and generate 4 random numbers

# Set the random seed and If you remove the seed, you’ll get different numbers each time.
np.random.seed(123)

# Generate 4 random numbers between 0 and 1
random_nums = np.random.rand(4)
print(random_nums)


[0.69646919 0.28613933 0.22685145 0.55131477]


Question 12: Linear Algebra Operations


In [ ]:
# Q12.1: Calculate the dot product of account balance and credit score columns
import numpy as np

dot_product=np.dot(customer_data[:,1],customer_data[:,2])
print(dot_product)

81943850


In [ ]:
# Q12.2: Calculate the cross product of first two rows
cross_product=np.cross(customer_data[:,1],customer_data[:,2])
print(cross_product)


In [ ]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
price_norm = np.linalg.norm(customer_data[:, 1])
print(price_norm)

40922.37407580357


In [ ]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
matrix_3x3 = np.array([[[2, 3], [1, 4]]])
determinant = np.linalg.det(matrix_3x3)
print(matrix_3x3)
print(determinant)

[[[2 3]
  [1 4]]]
[5.]


In [ ]:
# Q12.5: Calculate the inverse of the 3x3 matrix
inverse_matrix = np.linalg.inv(matrix_3x3)
print(inverse_matrix)

[[ 0.8 -0.6]
 [-0.2  0.4]]


 QUESTION 13: STRING OPERATIONS


In [ ]:
# Q13.1: Convert all customer IDs to strings
product_ids_str = customer_data[:, 0].astype(str)
print(product_ids_str)

['1005' '1001' '1008' '1006' '1009' '1004' '1002' '1007' '1010' '1003']


In [ ]:
# Q13.2: Check if any customer ID contains '100'
contains_100 = np.char.find(product_ids_str, '100') >= 0
print(contains_100)

In [ ]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
product_ids_upper = np.char.upper(product_ids_str)
print(product_ids_upper)

In [ ]:
# Q13.4: Count the length of each customer ID string
id_lengths = np.char.str_len(product_ids_str)
print(id_lengths)

[4 4 4 4 4 4 4 4 4 4]


In [ ]:
# Q13.5: Replace '100' with 'CUST' in customer IDs
replaced_ids = np.char.replace(product_ids_str, '100', 'PROD')
print(replaced_ids)

['PROD5' 'PROD1' 'PROD8' 'PROD6' 'PROD9' 'PROD4' 'PROD2' 'PROD7' '1010'
 'PROD3']


# QUESTION 14: DATE AND TIME OPERATIONS


In [ ]:
# Q14.1: Convert years active to months

conver_months=customer_data[:,4]*12
print(conver_months)

[ 96  60 180  36  72  48 144  24 108  84]


In [ ]:
# Q14.2: Calculate the average years active

average_active=np.mean(customer_data[:,4])
print(average_active)

7.1


In [ ]:
# Q14.3: Find customers who have been active for more than 5 years

customer_data[customer_data[:,4]>5]

array([[ 1001, 15420,   720,    25,     8],
       [ 1003, 19350,   810,    40,    15],
       [ 1005, 12800,   690,    20,     6],
       [ 1007, 17500,   780,    35,    12],
       [ 1009, 16000,   730,    28,     9],
       [ 1010, 11000,   500,    18,     7]])

In [ ]:
# Q14.4: Calculate the total time all customers have been active (in years)

np.sum(customer_data[:, 4])


np.int64(71)

In [ ]:
# Q14.5: Find the customer with the shortest time active
customer_data[customer_data[:,4].argmin()]


array([1008, 4200,  610,    9,    2])

Question 15: Advanced Array Operations


In [ ]:
# Q15.1: Apply a function to calculate 5% interest on all account balances
customers=customer_data[:, 1] * 1.05

print(customers)

[16191.   8851.5 20317.5  5901.  13440.  10237.5 18375.   4410.  16800.
 11550. ]


In [ ]:
# Q15.2: Use np.where to categorize customers by balance ranges

# Categorize using np.where
categories = np.where(
    customer_data[:, 1] < 5000, "Low",
    np.where(customer_data[:, 1] <= 7000, "Medium", "High")
)

print(categories)


['High' 'High' 'High' 'Medium' 'High' 'High' 'High' 'Low' 'High' 'High']


In [ ]:
# Q15.3: Use np.select to categorize customers by credit score ranges

balances=customer_data[:,2]
conditions = [
    balances < 500,
    (balances >= 500) & (balances <= 700),
    balances > 700
]

# Define choices
choices = ["Low", "Medium", "High"]

# Apply np.select
categories = np.select(conditions, choices, default="Unknown")

print(categories)

['High' 'Medium' 'High' 'Medium' 'Medium' 'Low' 'High' 'Medium' 'High'
 'Medium']


In [ ]:
# Q15.4: Use np.piecewise to apply different interest rates based on balance


def low_price(x): return x * 0.9  # 10% interest rate
def mid_price(x): return x * 1.0  # No change
def high_price(x): return x * 1.1  # 10% markup

discounted_prices = np.piecewise(
    customer_data[:, 1],
    [customer_data[:, 1] < 20, (customer_data[:, 1] >= 20) & (customer_data[:, 1] < 50), customer_data[:, 1] >= 50],
    [low_price, mid_price, high_price]
)
print(discounted_prices)


[16962  9273 21285  6182 14080 10725 19250  4620 17600 12100]


In [ ]:
# Q15.5: Use np.apply_along_axis to calculate the sum of each row

import numpy as np


# Use np.apply_along_axis to calculate row sums
row_sums = np.apply_along_axis(np.sum, axis=1, arr=customer_data)

print(row_sums)


[17174 10104 21218  7174 14521 11225 19334  5829 17776 12535]


Question 16: Array Concatenation and Stacking


In [ ]:
# Q16.1: Concatenate two arrays horizontally using np.hstack()
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.hstack((a, b))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.vstack((a, b))
print(result)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.concatenate((a, b))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Q16.4: Stack arrays depth-wise using np.dstack()
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dstack((a, b))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
# Q16.5: Create a column stack using np.column_stack()
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.column_stack((a, b))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


Question 17: Array Splitting Operations


In [ ]:
# Q17.1: Split an array into 3 equal parts using np.split()
arr=np.random.randint(1,100,(3,3))
np.split(arr,3)

# Q17.3: Split an array horizontally using np.hsplit()

# Q17.4: Split an array vertically using np.vsplit()




[array([[22,  2, 19]]), array([[57,  7, 18]]), array([[58, 24, 52]])]

In [ ]:
# Q17.2: Split an array at specific indices using np.split()
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Split at indices 2 and 5
result = np.split(arr, [1, 5])

print(result)


[array([10]), array([20, 30, 40, 50]), array([60, 70])]


In [ ]:
# Q17.3: Split an array horizontally using np.hsplit()
arr=np.random.randint(1,100,(3,4))
print(arr)
np.hsplit(arr,2)

[[ 7 85 49 16]
 [23 38 73  6]
 [84 44 31 96]]


[array([[ 7, 85],
        [23, 38],
        [84, 44]]),
 array([[49, 16],
        [73,  6],
        [31, 96]])]

In [6]:
# Q17.4: Split an array vertically using np.vsplit()
arr=np.random.randint(1,100,(4,4))
print(arr)
np.vsplit(arr,2)

[[92 64 20 45]
 [15 77 75 19]
 [76 50 83 99]
 [47 78 57 77]]


[array([[92, 64, 20, 45],
        [15, 77, 75, 19]]),
 array([[76, 50, 83, 99],
        [47, 78, 57, 77]])]

In [ ]:
# Q17.5: Split an array into equal chunks using np.array_split()
arr=np.random.randint(1,100,(3,4))
print(arr)
np.array_split(arr,2)

[[24  6 10  4]
 [39 78  3 41]
 [83 66 52 15]]


[array([[24,  6, 10,  4],
        [39, 78,  3, 41]]),
 array([[83, 66, 52, 15]])]

Question 18: Array Repetition and Tiling


In [7]:
# Q18.1: Repeat each element of an array 3 times using np.repeat()
arr=np.array([1,2,3])
np.repeat(arr,3)


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [8]:
# Q18.2: Repeat an entire array 2 times using np.tile()
arr = np.array([1, 2, 3])
result = np.tile(arr, 2)
print(result)


[1 2 3 1 2 3]


In [9]:
# Q18.3: Repeat a 2D array using np.tile()
arr = np.array([[1, 2], [3, 4]])
result = np.tile(arr, (2, 3))  # repeat 2 times vertically, 3 times horizontally
print(result)


[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [10]:
# Q18.4: Create a pattern using np.tile()
pattern = np.array([1, 0])
result = np.tile(pattern, 5)
print(result)


[1 0 1 0 1 0 1 0 1 0]


In [11]:
# Q18.5: Repeat elements with different counts using np.repeat()
arr = np.array([1, 2, 3])
result = np.repeat(arr, [1, 2, 3])  # repeat 1 once, 2 twice, 3 thrice
print(result)


[1 2 2 3 3 3]


Question 19: Array Comparison and Logical Operations


In [12]:
# Q19.1: Compare two arrays for equality using np.array_equal()
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = np.array([1, 2, 4])

print(np.array_equal(a, b))  # True
print(np.array_equal(a, c))  # False







True
False


In [13]:
# Q19.2: Check if arrays are close using np.allclose()
x = np.array([1.0, 2.0, 3.00001])
y = np.array([1.0, 2.0, 3.0])

print(np.allclose(x, y))  # True


True


In [14]:
# Q19.3: Apply logical AND operation between arrays
a = np.array([True, False, True])
b = np.array([True, True, False])

result = np.logical_and(a, b)
print(result)


[ True False False]


In [15]:
# Q19.4: Apply logical OR operation between arrays
result = np.logical_or(a, b)
print(result)


[ True  True  True]


In [16]:
# Q19.5: Apply logical NOT operation to an array
result = np.logical_not(a, b)
print(result)


[False  True False]


Question 20: Array Set Operations


In [17]:
# Q20.1: Find unique elements in an array using np.unique()
import numpy as np

arr = np.array([1, 2, 2, 3, 4, 4, 5])
result = np.unique(arr)
print(result)







[1 2 3 4 5]


In [18]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
result = np.intersect1d(a, b)
print(result)


[3 4]


In [19]:
# Q20.3: Find the union of two arrays using np.union1d()
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])
result = np.union1d(a, b)
print(result)


[1 2 3 4 5]


In [20]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5])
result = np.setdiff1d(a, b)
print(result)


[1 2]


In [21]:
# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
result = np.setxor1d(a, b)
print(result)


[1 2 5 6]
